#!/usr/bin/env python
# coding: utf-8

# used for testing to generate the t/tshark_jpp.json

import argparse
import logging
import simplejson as json
from sslf.reader.tshark import Reader as tshark

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="this is program") # options and program name are automatic
    parser.add_argument('-q', '--quiet', action='store_true')
    parser.add_argument('-n', '--no-dedup', action='store_true')
    parser.add_argument('--output', type=str, default='t/tshark_jpp.json')
    parser.add_argument('--input', type=str, default='t/tshark.json')

    args = parser.parse_args()

    if not args.quiet:
        logging.basicConfig(level=logging.DEBUG)

    with open(args.input, 'r') as fh:
        dat = json.load(fh)

    ts = tshark()
    jdat = ts.json_post_process(dat, dedup=not args.no_dedup)
    with open(args.output, 'w') as fh:
        json.dump(jdat, fh, indent=2, sort_keys=True)
